# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    labels: ["dependencies", "github-actions"]
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      github-actions:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    labels: ["dependencies", "docker"]
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      docker:
        patterns: ["*"]
        update-types: ["minor", "patch"]
